people:
    pattern:  /
    defaults: { _controller: "CognitiveTestBundle:People:index" }

people_create:
    pattern:  /create
    defaults: { _controller: "CognitiveTestBundle:People:create", _format: json }

people_list:
    pattern:  /read
    defaults: { _controller: "CognitiveTestBundle:People:read", _format: json }

people_update:
    pattern:  /update
    defaults: { _controller: "CognitiveTestBundle:People:update", _format: json }

people_delete:
    pattern:  /delete
    defaults: { _controller: "CognitiveTestBundle:People:delete", _format: json }
