<?php

namespace Cognitive\TestBundle\Entity;

//use Doctrine\ORM\EntityRepository;
//use Symfony\Component\HttpFoundation\JsonResponse;

/**
 * CityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CityRepository extends TestBaseRepository
{

}
