Cognitive\TestBundle\Entity\City:
    properties:
        name:
            - NotBlank: ~

Cognitive\TestBundle\Entity\Education:
    properties:
        name:
            - NotBlank: ~

Cognitive\TestBundle\Entity\People:
    properties:
        name:
            - NotBlank: ~
            
